package pokemon;

public enum GameState {
  DEFAULT,
  BATTLE_DEFAULT,
  BATTLE_WAIT_ON_ENEMY,
  BATTLE_CHOOSE_ATTACK,
  BATTLE_ATTACK_ANIMATION,
  BATTLE_VIEW_POKEMON,
  BATTLE_SWITCH_ANIMATION,
  SAVE,
  VIEW_POKEDEX,
  VIEW_POKEMON,
  VIEW_PARTY,
  VIEW_ITEMS,
  VIEW_SELF,
}
